### ISSUE TITLE
Please remove `__MACOSX` dir

### ISSUE THREAD

**Issue by pcav** [socrata/Socrata#8]
This causes unwanted red warning in the plugin interface.
Thanks.

**Comment by PeterAustinMoore** [comment]
Should be removed as part of #9 - https://plugins.qgis.org/plugins/Socrata/version/2.1/ (awaiting approval)

**Comment by PeterAustinMoore** [comment]
@pcav if you have a moment, can you confirm this was resolved in v2.1?

**Comment by pcav** [comment]
Apparently yes. Zip file to be checked.
Cheers.

On 3 March 2020 23:56:57 CET, Peter Moore <notifications@github.com> wrote:
>@pcav if you have a moment, can you confirm this was resolved in v2.1? 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/socrata/Socrata/issues/8#issuecomment-594214374

-- 
Please excuse my brevity.
