### ISSUE TITLE
Re-adding of Previously Requested Layer and Dataset ID Issue 

### ISSUE THREAD

**Issue by TwoWaves** [socrata/Socrata#9]
I'm connecting to data.ny.gov, using QGIS version 3.6 and Socrata plugin version 2.0. 

After I connect to the domain and select "Get Maps", the plugin functions as expected taking me to the list of available layers, and it then successfully loads the layer chosen when I click on it and then select "OK".  For example I loaded the 2000 census block layer.  However, if I then go back and enter in a unique 4 by 4 Socrata identifier sequence/dataset ID for a different layer on the Download tab and hit "OK" the census block layer is reloaded in QGIS rather than the new layer.

Additionally, I am finding that the same census block layer does not load in the map if I start a new QGIS session and use the dataset ID to connect to the layer.  data.ny.gov and ID: t3ph-3ztd 

Is there a format that must be followed for the dataset ID?
Thanks for any insight.

**Comment by PeterAustinMoore** [comment]
@TwoWaves thanks for raising this - I can reproduce the issue and will take a look at where that is breaking.

**Comment by PeterAustinMoore** [comment]
@TwoWaves Approval pending: https://plugins.qgis.org/plugins/Socrata/version/2.1/

**Comment by TwoWaves** [comment]
This is fantastic!  I've been working with the plugin this morning and it's working great.  Thanks for the quick response.  I can't tell you how big an impact this will make in our user community.
Cheers
